name: Information

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      crq:
        description: "CRQ"
        type: string
        required: false
      release_note_link:
        description: "Release Note Link"
        type: string
        required: false
      release_description:
        description: "Release Description"
        type: string
        required: true

jobs:
  ## Information about the release
  environment:
    name: Deployment information
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Show deployment information
        run: |        
            echo "branch: ${GITHUB_REF#refs/heads/}"
            echo "env: ${{ github.event.inputs.environment }}"
            echo "crq: ${{ github.event.inputs.crq }}"
            echo "release note link: ${{ github.event.inputs.release_note_link }}"
            echo "release description: ${{ github.event.inputs.release_description }}"
