name: Information

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      release_note:
        type: string
        required: true

jobs:
  ## Information about the release
  environment:
    name: Deployment information
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Show deployment information
        run: |        
            echo "branch: ${GITHUB_REF#refs/heads/}"
            echo "env: ${{ github.event.inputs.environment }}"
            echo "release notes: ${{ github.event.inputs.release_note }}"
