name: Release Notes

on:
  workflow_call:
    inputs:
      release_note:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
   ## Creates the release notes
  release:
    name: Create Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release-${{ env.NOW}}"
          prerelease: false
          title: ${{ inputs.release_note }} - (${{ inputs.environment }})
