name: Release Notes

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      crq:
        description: "CRQ"
        type: string
        required: false
      release_note_link:
        description: "Release Note Link"
        type: string
        required: false
      release_description:
        description: "Release Description"
        type: string
        required: true

jobs:
   ## Creates the release notes
  release:
    name: Create Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-${{ env.NOW}}"
          prerelease: false
          title: ${{ inputs.release_description }} - ${{ env.NOW}} - (${{ inputs.environment }})
